sudo: required
language: generic
services:
  - docker
before_install:
  - echo "Start creating an image with Dockerfile"
  - docker build -t scp0000/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true scp0000/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test Succeeded"