sudo: required
language: generic
services:
  - docker
before_install:
  - echo "Start creating an image with Dockerfile"
  - docker build -t scp0000/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true scp0000/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test Succeeded"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-082186817198"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY